FROM vsplate/centos_apache2_php5_mysql5:latest
MAINTAINER Ambulong <zeng.ambulong@gmail.com>

COPY index.php /var/www/html/index.php

COPY sqlilabs /var/www/html/sqlilabs

RUN chmod -R 777 /var/www/html
