# The Travis setup:
# - run testsuite for every PHP version
# - run lint for every PHP version
# - run Selenium for single PHP version

language: php

php:
  - "7.0"
  - "5.6"
  - "5.5"
  - hhvm

sudo: false

env:
  matrix:
    - PHPUNIT_ARGS="--exclude-group selenium"
  global:
    - TESTSUITE_USER=root
    - TESTSUITE_PASSWORD=root
    - TESTSUITE_URL=http://127.0.0.1:8000

install:
  - pip install --user codecov
  - ./test/install-runkit
  - ./test/install-browserstack
  - composer install --dev --no-interaction

before_script:
  - if [ $TRAVIS_PHP_VERSION != "hhvm" ] ; then phpenv config-add test/php-noprofile.ini ; fi
  - export PATH=~/.composer/vendor/bin/:$PATH
  - mysql -uroot -e "CREATE DATABASE test"
  - mysql -uroot < sql/create_tables.sql
  - mysql -uroot -e "SET PASSWORD = PASSWORD('$TESTSUITE_PASSWORD')"
  - ./test/start-local-server

script:
  - ant clean
  - ant locales
  - ant lint
  - set -e;
    if [ $TRAVIS_PHP_VERSION == "hhvm" ] ; then
    ant phpunit-hhvm ;
    else
    if [ ! -z "$SELENIUM" ] ; then
    ant phpunit-nocoverage ;
    else
    ant phpunit ;
    fi ;
    fi

after_script:
  - if [ -f vendor/bin/coveralls ] ; then php vendor/bin/coveralls -v || true ; fi
  - if [ -f vendor/bin/codacycoverage ] ; then php vendor/bin/codacycoverage clover || true ; fi
  - codecov
  - if [ -f php.log ] ; then cat php.log ; fi

matrix:
  allow_failures:
    - php: 5.6
      env: PHPUNIT_ARGS="--group selenium" SELENIUM="yes"
  fast_finish: true
  include:
    - php: 5.6
      env: PHPUNIT_ARGS="--group selenium" SELENIUM="yes"
cache:
  directories:
    - $HOME/.composer/cache/
    - $HOME/browserstack
    - $HOME/runkit
# trigger Buildtime Trend Service to parse Travis CI log
notifications:
  webhooks:
    - https://buildtimetrend.herokuapp.com/travis
